# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/adventures_with_ip.xdc

# Block Designs: bd/audio/audio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio || ORIG_REF_NAME==audio} -quiet] -quiet

# IP: bd/audio/ip/audio_processing_system7_0_0/audio_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_processing_system7_0_0 || ORIG_REF_NAME==audio_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_zed_audio_ctrl_0_0/audio_zed_audio_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_zed_audio_ctrl_0_0 || ORIG_REF_NAME==audio_zed_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_xbar_0/audio_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_xbar_0 || ORIG_REF_NAME==audio_xbar_0} -quiet] -quiet

# IP: bd/audio/ip/audio_ps7_0_axi_periph_0/audio_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_ps7_0_axi_periph_0 || ORIG_REF_NAME==audio_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/audio/ip/audio_rst_ps7_0_100M_0/audio_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_rst_ps7_0_100M_0 || ORIG_REF_NAME==audio_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_gpio_0_0/audio_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_gpio_0_0 || ORIG_REF_NAME==audio_axi_gpio_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_gpio_1_0/audio_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_gpio_1_0 || ORIG_REF_NAME==audio_axi_gpio_1_0} -quiet] -quiet

# IP: bd/audio/ip/audio_auto_pc_0/audio_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_auto_pc_0 || ORIG_REF_NAME==audio_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/minji/Desktop/AudioMixer_Project/AudioMixer_Vivado/AudioMixer_Vivado/AudioMixer_Vivado.gen/sources_1/bd/audio/audio_ooc.xdc
